---
version: "3.3"

services:
  db:
    image: mysql:5.7
    ports:
      - "3345:3306"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

networks:
  backend:

volumes:
  db_data: