---
version: "3.3"

services:
  
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  api:
    build:
      context: ../ 
    ports:
      - "3333:4000"
    env_file:
      - ../.env
