---
version: "3.3"

services:
  
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  api:
    build:
      context: ../ 
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env

volumes:
  db_data:
